### ISSUE TITLE
Update this line to use the MONGO_URL for e2e test

### ISSUE THREAD

**Issue by fakel** [Roxana-Vargas/LIM015-burger-queen-api#13]
Replace https://github.com/Roxana-Vargas/LIM015-burger-queen-api/blob/cfc74c01a0f8941315292835a959f9f57116ef3c/src/config.js#L2

with: `exports.dbUrl = process.env.MONGO_URL || process.env.DB_URL || 'mongodb://localhost:27017/test';`

**Comment by unjust** [comment]
@fakel hay algo en la documentacion de mongo o shelf que dice es necesario a definir eso? Solo quiero saber como sabes :)

**Comment by fakel** [comment]
Bueno, está mencionado en la documentación del shelf pero ciertamente no es 100% explicito:

https://github.com/shelfio/jest-mongodb#3-configure-mongodb-client
